pipeline {
    agent any  // Define que el pipeline puede ejecutarse en cualquier agente disponible (máquina de Jenkins)

    environment {
        NODE_HOME = '/usr/local/bin/node'  // Ajusta la ruta si es diferente en tu sistema
        PATH = "${NODE_HOME}/bin:${env.PATH}"
    }

    stages {
        stage('Clonar Repositorio') {
            steps {
               git 'https://Serghio07:<tu_token>@github.com/CamiloMendez23/ProyectoSIS312.git'
  // Clona el repositorio de GitHub
            }
        }
        
        stage('Instalar Dependencias') {
            steps {
                script {
                    sh 'npm install'  // Instala las dependencias del proyecto React
                }
            }
        }

        stage('Construir Aplicación') {
            steps {
                script {
                    sh 'npm run build'  // Construye la aplicación en producción
                }
            }
        }
        
        stage('Desplegar en Ambiente Local') {
            steps {
                script {
                    // Comando de despliegue, por ejemplo:
                    sh 'npm run deploy'  // Esto debería hacer el despliegue de la aplicación
                }
            }
        }
    }

    post {
        always {
            cleanWs()  // Limpiar el workspace después de ejecutar el pipeline
        }
    }
}
