pipeline {
    agent any
    tools {
        nodejs 'Node_18'  // Aquí se define la versión de Node.js, similar a como se define Maven
    }

    stages {
        stage('Clonar Repositorio') {
            steps {
                git branch: 'main', url: 'https://github.com/CamiloMendez23/ProyectoSIS312.git'
            }
        }


        stage('Instalar Dependencias') {
            steps {
                // Asegurarse de estar en la carpeta donde está el package.json y ejecutar npm install
                dir('frontend') {
                    sh 'npm install'
                }
            }
        }

        stage('Build') {
            steps {
                // Ejecutar el build de producción
                dir('frontend') {
                    sh 'npm run build'
                }
            }
        }

        stage('Deploy') {
            steps {
                // Aquí podrías agregar un paso para desplegar, como subir el build a un servidor o contenedor
                echo 'Desplegando la aplicación...'
                // Este paso depende de tu estrategia de despliegue
            }
        }
    }

    post {
        always {
            cleanWs()  // Limpiar el workspace siempre que termine el pipeline
        }
    }
}
