# Realizado por: Camilo, Sergio y Johan
# Este archivo define los servicios y configuraciones para Docker Compose
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080" # Map host port 8081 to container port 8080
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins
networks:
  jenkins:
    driver: bridge
volumes:
  jenkins_home: